language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - ./vendor/bin/phplint

script: ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml

matrix:
  fast_finish: true